In [1]:
import qe.myqengine as qe

In [2]:
univ = qe.ScreenUniverse('FG_CONSTITUENTS(SP50,0,CLOSE)=1')
ts = qe.TimeSeries(start_date='0Y-5AY',end_date = '0Y')
df = qe.calculate(universe = univ, dates =ts,formulas = ['CT_TICKER_HIST'])
df

In [8]:
df.data

           DATE UNIVERSE CT_TICKER_HIST
0      20171229     CTAS           CTAS
1      20171229      SCG            SCG
2      20171229    LLL.1            LLL
3      20171229      RTX            UTX
4      20171229      WEC            WEC
...         ...      ...            ...
30785  20221230     PARA           PARA
30786  20221230     CARR           CARR
30787  20221230     OTIS           OTIS
30788  20221230     MTCH           MTCH
30789  20221230      WBD            WBD

[30790 rows x 3 columns]

In [5]:
unique_tickers = df.data.CT_TICKER_HIST.unique()

In [6]:
from misc.utils import get_google_trends

In [35]:
import pandas as pd
df_full = pd.DataFrame()
for ticker in unique_tickers:
    df_g = get_google_trends(search_list=[ticker],start_date = '2017-12-29',end_date = '2022-12-30')
    df_full = pd.concat([df_full,df_g.iloc[:,0]],axis=1)

df_full

'request'

AttributeError: 'NoneType' object has no attribute 'iloc'

In [36]:
df_full

,CTAS,SCG,LLL,UTX,WEC,MAA,AES,FAST,ANSS,ED,...,KMI,AAL,PNW,SIG,BRK.B,GM,KMX,DPS,ABBV,CSRA
2017-12-31,72,49,51,33,12,26,73,63,42,90,...,44,20,39,69,31,69,72,83,27,29
2018-01-07,70,39,52,49,13,28,93,68,37,82,...,29,21,39,85,38,79,51,87,30,36
2018-01-14,59,34,50,40,14,27,92,58,38,83,...,49,20,40,79,37,71,58,82,28,35
2018-01-21,58,36,51,47,15,33,91,60,42,100,...,31,22,42,84,36,72,51,85,55,36
2018-01-28,72,35,60,43,21,28,96,58,47,92,...,39,20,39,88,37,77,69,90,48,38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-11-27,71,23,49,7,13,19,76,62,36,43,...,24,15,57,77,30,58,54,86,25,22
2022-12-04,71,24,48,8,16,21,71,61,29,43,...,34,16,52,74,23,59,49,90,22,20
2022-12-11,73,25,46,7,15,20,70,65,31,49,...,36,17,53,72,27,60,49,91,20,23
2022-12-18,72,29,49,7,15,21,71,70,35,43,...,36,19,61,71,26,61,89,89,22,23
2022-12-25,69,26,47,7,13,23,53,70,22,45,...,33,18,55,68,25,61,56,78,19,17

In [23]:
rerun_tickers = set(unique_tickers)- set(df_full.columns)

In [24]:
import pandas as pd
df_full2 = pd.DataFrame()
for ticker in rerun_tickers:
    df_g = get_google_trends(search_list=[ticker],start_date = '2017-12-29',end_date = '2022-12-30')
    df_full2 = pd.concat([df_full2,df_g.iloc[:,0]],axis=1)

df_full2

'request'

AttributeError: 'NoneType' object has no attribute 'iloc'

In [37]:
df_full=pd.concat([df_full,df_full2],axis=1)

In [28]:
rerun_tickers2 = set(rerun_tickers)- set(df_full.columns)

In [38]:
import pandas as pd
df_full3 = pd.DataFrame()
for ticker in list(rerun_tickers2)[1:]:
    df_g = get_google_trends(search_list=[ticker],start_date = '2017-12-29',end_date = '2022-12-30')
    df_full3 = pd.concat([df_full3,df_g.iloc[:,0]],axis=1)

df_full3

,CA,EXR,HCA,ETSY,WST,FTV,J,NLOK,MRNA,CRL,...,CBG,ENPH,CPRT,STE,FOXA,FSLR,BKNG,HII,ACGL,TYL
2017-12-31,89,77,63,38,43,51,75,2,4,33,...,36,4,24,54,33,44,1,47,78,66
2018-01-07,86,74,67,37,50,52,79,0,8,43,...,40,3,15,57,41,71,3,50,74,80
2018-01-14,81,79,67,36,50,49,76,3,8,41,...,39,2,20,58,39,42,3,46,39,75
2018-01-21,80,76,68,38,52,50,81,2,10,41,...,35,7,18,56,49,100,1,46,49,70
2018-01-28,85,75,78,39,55,50,79,0,10,43,...,37,3,0,54,41,51,5,46,52,74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-11-27,50,79,75,82,66,20,64,7,24,45,...,76,34,18,47,21,25,17,75,55,78
2022-12-04,51,81,76,86,54,20,72,7,28,48,...,77,34,21,45,15,23,19,78,61,74
2022-12-11,49,81,76,76,70,21,66,8,32,47,...,76,27,19,47,32,21,18,84,36,76
2022-12-18,53,76,67,64,53,22,67,8,22,45,...,77,27,14,52,20,25,16,85,89,81
2022-12-25,53,76,62,68,49,23,69,6,16,42,...,82,24,24,46,16,22,10,83,53,81

In [34]:
df_full=pd.concat([df_full,df_full3],axis=1)

Empty DataFrame
Columns: []
Index: []

In [39]:
df_full

,CTAS,SCG,LLL,UTX,WEC,MAA,AES,FAST,ANSS,ED,...,QRVO,ZTS,DWDP,CTRA,VIAB,M,XYL,ABMD,DUK,BHGE
2017-12-31,72,49,51,33,12,26,73,63,42,90,...,15,61,41,14,53,78,49,27,19,39
2018-01-07,70,39,52,49,13,28,93,68,37,82,...,17,59,44,14,78,83,51,26,19,44
2018-01-14,59,34,50,40,14,27,92,58,38,83,...,19,77,39,18,61,76,48,24,17,46
2018-01-21,58,36,51,47,15,33,91,60,42,100,...,19,67,40,16,52,76,53,26,19,64
2018-01-28,72,35,60,43,21,28,96,58,47,92,...,60,76,50,18,41,77,62,26,18,57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-11-27,71,23,49,7,13,19,76,62,36,43,...,8,46,1,25,20,81,56,14,18,1
2022-12-04,71,24,48,8,16,21,71,61,29,43,...,6,54,0,25,19,83,67,12,19,1
2022-12-11,73,25,46,7,15,20,70,65,31,49,...,7,62,0,28,17,82,68,8,20,1
2022-12-18,72,29,49,7,15,21,71,70,35,43,...,9,49,0,26,34,86,69,20,20,0
2022-12-25,69,26,47,7,13,23,53,70,22,45,...,8,50,0,24,10,82,57,13,21,2

In [41]:
df_full.to_csv('../data/Backtesting/google_trends_ticker_2017-2022.csv')