In [2]:
import pandas as pd
import qe.myqengine as qe

In [4]:
univ = qe.ScreenUniverse(universe_expr='((ETP_EXCHANGE(COUNTRY)="US") AND ISAV(ETP_STRUCTURE(ACTIVELY_MANAGE,CODE))=1 AND (ISAV(P_PRICE(0)=1)))=1')
ts = qe.TimeSeries(start_date = '0M')
data_dict = {"class":'ETP_CLASS(ASSET,TEXT)',
             "strat":'ETP_STRATEGY(STRATEGY,TEXT)',
             "class":'ETP_CLASS(REGION,TEXT)',
             "active_mgt":'ETP_STRUCTURE(ACTIVELY_MANAGE,CODE)',
             "fund_flows_1m":'ETP_FUND_FLOWS(0,1MON)',
             "aum":'ETP_AUM(0,ACT)'}
calc = qe.Calculation(universe=univ,dates = ts,data_dict=data_dict)
calc.query()
calc.data

,DATE,UNIVERSE,class,strat,active_mgt,fund_flows_1m,aum
0,20230831,FPXI,Global Ex-U.S.,Time Since Launch,0.0,-6157650.00,1.818182e+08
1,20230831,IWM,North America,Vanilla,0.0,92866155.85,5.479953e+10
2,20230831,EWN,Europe,Vanilla,0.0,-24431300.00,2.521404e+08
3,20230831,IYJ,North America,Vanilla,0.0,-15820151.40,1.224357e+09
4,20230831,IGN,North America,Vanilla,0.0,-6660944.10,5.591815e+07
...,...,...,...,...,...,...,...
3188,20230831,CSMD,North America,Active,1.0,NaN,1.299935e+06
3189,20230831,FTWO,North America,Vanilla,0.0,NaN,2.513000e+05
3190,20230831,USSE,North America,Active,1.0,NaN,5.018000e+05
3191,20230831,XOMO,North America,Buy-write,1.0,NaN,3.000000e+06
3192,20230831,AHLT,Global,Active,1.0,NaN,NaN