In [1]:
import qe.myqengine as qe
import pandas as pd

In [2]:
univ = qe.ScreenUniverse('FG_CONSTITUENTS(SP50,0,CLOSE)=1')
ts = qe.TimeSeries(start_date='0Y',end_date = '0Y')
df = qe.calculate(universe = univ, dates =ts,formulas = ['FREF_MARKET_VALUE_COMPANY(1,USD,1)',
                                                         'P_PRICE_RETURNS(1,0,+1/0/0,USD)',
                                                         'QFL_RBICS_CLASS(0,SECT)',
                                                         'QFL_FCFY(0,CT)',
                                                         'QFL_DY(0,CT)',
                                                         'QFL_OCFY(0,CT)',
                                                         'QFL_CFROIC(0,CT)',
                                                         'QFL_RES_RET_MOM(0,252D)']).data
df

,DATE,UNIVERSE,"FREF_MARKET_VALUE_COMPANY(1,USD,1)","P_PRICE_RETURNS(1,0,+1/0/0,USD)","QFL_RBICS_CLASS(0,SECT)","QFL_FCFY(0,CT)","QFL_DY(0,CT)","QFL_OCFY(0,CT)","QFL_CFROIC(0,CT)","QFL_RES_RET_MOM(0,252D)"
0,20221230,CTAS,45667.319579,-1.744830,1010,2.763833,1.018555,3.362941,28.298882,36.271250
1,20221230,RTX,148196.824753,-1.060250,4010,2.217081,2.179944,3.835483,5.427327,29.205132
2,20221230,WEC,29701.317422,0.245297,6510,-0.797791,3.327645,6.929582,8.405532,10.025299
3,20221230,MAA,18439.330973,7.089630,3025,4.882324,3.567106,5.472525,9.836174,-14.077759
4,20221230,AES,18776.068388,-4.117180,6510,-5.825304,2.307371,11.286850,9.448407,56.380142
...,...,...,...,...,...,...,...,...,...,...
498,20221230,PARA,11193.751497,37.203800,1515,-6.581443,5.687204,-3.390716,-0.921743,-34.717144
499,20221230,CARR,34796.840469,10.375700,4010,3.377380,1.793940,4.380307,9.405253,-0.333148
500,20221230,OTIS,32960.290177,5.005750,1010,3.797876,1.481292,4.168253,58.109020,8.712673
501,20221230,MTCH,11468.308493,30.441100,5520,4.194094,0.000000,4.765103,15.337886,-50.044674
502,20221230,WBD,23166.897710,56.329100,1515,7.069939,0.000000,10.227175,4.159946,-56.037330